### ISSUE TITLE
2.7-Request-response

### ISSUE THREAD

**Issue by mateusKoppe** [mateusKoppe/Laravel4Noobs#18]
Escrever uma página explicando sobre [Requests](https://laravel.com/docs/8.x/requests) e [Responses](https://laravel.com/docs/8.x/responses).

A ideia é falar sobre:
- Headers;
- Redirects;
- Flashed Session Data;
- Json;
- Acessar entradas, tanto vindo de body quando de query;

**Comment by NicolasPereira** [comment]
Fala Koppe, comecei a utilizar Requests personalizadas no trampo, acredito que eu possa te ajudar neste tópico. 

Vou começar a esboçar algumas coisas e fazer um PR, ok ?

**Comment by mateusKoppe** [comment]
Opa Nicolas!!

A ajuda seria muito bem vinda =D, no aguardo do pull request, se precisar só chamar na issue ou no discord ;)

**Comment by epcgrs** [comment]
@mateusKoppe Essa Issue tá completa já ?
vi que tem um PR já mergeado.

**Comment by mateusKoppe** [comment]
Esta completo sim, estou fechando a issue.
Se você alguma ideia de melhoria para essa doc sinta-se livre para mandar alterações.
