### ISSUE TITLE
Conteúdo Request-Response

### ISSUE THREAD

**Issue by NicolasPereira** [mateusKoppe/Laravel4Noobs#25]
Oi pessoal, o Mateus pediu para eu dar uma revisada geral no conteúdo e abrir algumas issues com o que vi de erro.

Pessoal, ao chegar na seção:
https://github.com/mateusKoppe/Laravel4Noobs/blob/master/2-Conceitos/7-Request-response.md

Não possui nenhum conteúdo, está apenas escrito que essa parte está em construção

**Comment by mateusKoppe** [comment]
Duplicated de #18
